-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- Link to schema: https://app.quickdatabasediagrams.com/#/d/GjrX8D
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.

-- Physical ERD
-- >- is many to 1. need to fix the
-- relationships to be sure the 1:1 1:many feet are all correcct
-- check if erd put everything in quotes

CREATE TABLE "DEPTS" (
    "DEPT_NO" VARCHAR   NOT NULL,
    "DEPT_NAME" VARCHAR   NOT NULL,
    CONSTRAINT "pk_DEPTS" PRIMARY KEY (
        "DEPT_NO"
     )
);

CREATE TABLE "TITLES" (
    "TITLE_ID" VARCHAR   NOT NULL,
    "TITLE" VARCHAR   NOT NULL,
    CONSTRAINT "pk_TITLES" PRIMARY KEY (
        "TITLE_ID"
     )
);

CREATE TABLE "EMPLOYEES" (
    "EMP_NO" INT   NOT NULL,
    "EMP_TITLE_ID" VARCHAR   NOT NULL,
    "BIRTH_DATE" DATE   NOT NULL,
    "FIRST_NAME" VARCHAR   NOT NULL,
    "LAST_NAME" VARCHAR   NOT NULL,
    "SEX" VARCHAR   NOT NULL,
    "HIRE_DATE" DATE   NOT NULL,
    CONSTRAINT "pk_EMPLOYEES" PRIMARY KEY (
        "EMP_NO"
     )
);

CREATE TABLE "DEPT_EMP" (
    "DEPT_NO" VARCHAR   NOT NULL,
    "EMP_NO" INT   NOT NULL,
    CONSTRAINT "pk_DEPT_EMP" PRIMARY KEY (
        "DEPT_NO","EMP_NO"
     )
);

CREATE TABLE "DEPT_MGR" (
    "DEPT_NO" VARCHAR   NOT NULL,
    "EMP_NO" INT   NOT NULL,
    CONSTRAINT "pk_DEPT_MGR" PRIMARY KEY (
        "DEPT_NO","EMP_NO"
     )
);

CREATE TABLE "SALARIES" (
    "EMP_NO" INT   NOT NULL,
    "SALARY" INT   NOT NULL,
    CONSTRAINT "pk_SALARIES" PRIMARY KEY (
        "EMP_NO"
     )
);

ALTER TABLE "EMPLOYEES" ADD CONSTRAINT "fk_EMPLOYEES_EMP_TITLE_ID" FOREIGN KEY("EMP_TITLE_ID")
REFERENCES "TITLES" ("TITLE_ID");

ALTER TABLE "DEPT_EMP" ADD CONSTRAINT "fk_DEPT_EMP_DEPT_NO" FOREIGN KEY("DEPT_NO")
REFERENCES "DEPTS" ("DEPT_NO");

ALTER TABLE "DEPT_EMP" ADD CONSTRAINT "fk_DEPT_EMP_EMP_NO" FOREIGN KEY("EMP_NO")
REFERENCES "EMPLOYEES" ("EMP_NO");

ALTER TABLE "DEPT_MGR" ADD CONSTRAINT "fk_DEPT_MGR_DEPT_NO" FOREIGN KEY("DEPT_NO")
REFERENCES "DEPTS" ("DEPT_NO");

ALTER TABLE "DEPT_MGR" ADD CONSTRAINT "fk_DEPT_MGR_EMP_NO" FOREIGN KEY("EMP_NO")
REFERENCES "EMPLOYEES" ("EMP_NO");

ALTER TABLE "SALARIES" ADD CONSTRAINT "fk_SALARIES_EMP_NO" FOREIGN KEY("EMP_NO")
REFERENCES "EMPLOYEES" ("EMP_NO");

